export type StapleItem = {
  name: string;
  quantity: string;
  measureUnit?: string;
  category:
    | 'spices'
    | 'grains'
    | 'proteins'
    | 'dairy'
    | 'produce'
    | 'baking'
    | 'condiments'
    | 'canned'
    | 'oils'
    | 'snacks'
    | 'misc';
};

export const commonIngredients = [
  'Salt',
  'Pepper',
  'Olive oil',
  'Garlic',
  'Onion',
  'Chicken breast',
  'Eggs',
  'Milk',
  'Butter',
  'Flour',
  'Sugar',
  'Rice',
  'Pasta',
  'Tomatoes',
  'Bell pepper',
  'Cumin',
  'Paprika',
  'Soy sauce',
];

export const staplePresetDetailed: StapleItem[] = [
  { name: 'Salt', quantity: '500', measureUnit: 'g', category: 'spices' },
  { name: 'Black pepper', quantity: '100', measureUnit: 'g', category: 'spices' },
  { name: 'Paprika', quantity: '100', measureUnit: 'g', category: 'spices' },
  { name: 'Cumin', quantity: '80', measureUnit: 'g', category: 'spices' },
  { name: 'Chili powder', quantity: '80', measureUnit: 'g', category: 'spices' },
  { name: 'Oregano', quantity: '60', measureUnit: 'g', category: 'spices' },
  { name: 'Basil', quantity: '60', measureUnit: 'g', category: 'spices' },
  { name: 'Cinnamon', quantity: '80', measureUnit: 'g', category: 'spices' },
  { name: 'Nutmeg', quantity: '50', measureUnit: 'g', category: 'spices' },
  { name: 'Coriander', quantity: '60', measureUnit: 'g', category: 'spices' },
  { name: 'Garlic powder', quantity: '80', measureUnit: 'g', category: 'spices' },
  { name: 'Onion powder', quantity: '80', measureUnit: 'g', category: 'spices' },
  { name: 'Curry powder', quantity: '80', measureUnit: 'g', category: 'spices' },
  { name: 'Red pepper flakes', quantity: '50', measureUnit: 'g', category: 'spices' },
  { name: 'Turmeric', quantity: '60', measureUnit: 'g', category: 'spices' },
  { name: 'Bay leaves', quantity: '1', measureUnit: 'pack', category: 'spices' },
  { name: 'Brown rice', quantity: '1', measureUnit: 'kg', category: 'grains' },
  { name: 'White rice', quantity: '1', measureUnit: 'kg', category: 'grains' },
  { name: 'Quinoa', quantity: '500', measureUnit: 'g', category: 'grains' },
  { name: 'Rolled oats', quantity: '1', measureUnit: 'kg', category: 'grains' },
  { name: 'Pasta', quantity: '1', measureUnit: 'kg', category: 'grains' },
  { name: 'Spaghetti', quantity: '1', measureUnit: 'kg', category: 'grains' },
  { name: 'Macaroni', quantity: '1', measureUnit: 'kg', category: 'grains' },
  { name: 'Couscous', quantity: '500', measureUnit: 'g', category: 'grains' },
  { name: 'Bread flour', quantity: '1', measureUnit: 'kg', category: 'baking' },
  { name: 'All-purpose flour', quantity: '1', measureUnit: 'kg', category: 'baking' },
  { name: 'Whole wheat flour', quantity: '1', measureUnit: 'kg', category: 'baking' },
  { name: 'Cornmeal', quantity: '500', measureUnit: 'g', category: 'baking' },
  { name: 'Baking powder', quantity: '1', measureUnit: 'can', category: 'baking' },
  { name: 'Baking soda', quantity: '1', measureUnit: 'box', category: 'baking' },
  { name: 'White sugar', quantity: '1', measureUnit: 'kg', category: 'baking' },
  { name: 'Brown sugar', quantity: '1', measureUnit: 'kg', category: 'baking' },
  { name: 'Powdered sugar', quantity: '500', measureUnit: 'g', category: 'baking' },
  { name: 'Yeast', quantity: '1', measureUnit: 'pack', category: 'baking' },
  { name: 'Honey', quantity: '500', measureUnit: 'g', category: 'condiments' },
  { name: 'Maple syrup', quantity: '250', measureUnit: 'ml', category: 'condiments' },
  { name: 'Olive oil', quantity: '1', measureUnit: 'l', category: 'oils' },
  { name: 'Vegetable oil', quantity: '1', measureUnit: 'l', category: 'oils' },
  { name: 'Sesame oil', quantity: '250', measureUnit: 'ml', category: 'oils' },
  { name: 'Soy sauce', quantity: '500', measureUnit: 'ml', category: 'condiments' },
  { name: 'Fish sauce', quantity: '250', measureUnit: 'ml', category: 'condiments' },
  { name: 'Hot sauce', quantity: '200', measureUnit: 'ml', category: 'condiments' },
  { name: 'Vinegar', quantity: '750', measureUnit: 'ml', category: 'condiments' },
  { name: 'Balsamic vinegar', quantity: '500', measureUnit: 'ml', category: 'condiments' },
  { name: 'Apple cider vinegar', quantity: '750', measureUnit: 'ml', category: 'condiments' },
  { name: 'Ketchup', quantity: '500', measureUnit: 'ml', category: 'condiments' },
  { name: 'Mustard', quantity: '250', measureUnit: 'ml', category: 'condiments' },
  { name: 'Mayonnaise', quantity: '400', measureUnit: 'g', category: 'condiments' },
  { name: 'Tomato paste', quantity: '3', measureUnit: 'cans', category: 'canned' },
  { name: 'Canned tomatoes', quantity: '3', measureUnit: 'cans', category: 'canned' },
  { name: 'Canned beans', quantity: '4', measureUnit: 'cans', category: 'canned' },
  { name: 'Chickpeas', quantity: '2', measureUnit: 'cans', category: 'canned' },
  { name: 'Lentils', quantity: '500', measureUnit: 'g', category: 'grains' },
  { name: 'Black beans', quantity: '500', measureUnit: 'g', category: 'grains' },
  { name: 'Kidney beans', quantity: '500', measureUnit: 'g', category: 'grains' },
  { name: 'Peanut butter', quantity: '400', measureUnit: 'g', category: 'snacks' },
  { name: 'Almonds', quantity: '300', measureUnit: 'g', category: 'snacks' },
  { name: 'Walnuts', quantity: '300', measureUnit: 'g', category: 'snacks' },
  { name: 'Raisins', quantity: '300', measureUnit: 'g', category: 'snacks' },
  { name: 'Breakfast cereal', quantity: '500', measureUnit: 'g', category: 'snacks' },
  { name: 'Granola', quantity: '500', measureUnit: 'g', category: 'snacks' },
  { name: 'Coffee', quantity: '500', measureUnit: 'g', category: 'misc' },
  { name: 'Tea bags', quantity: '50', measureUnit: 'pcs', category: 'misc' },
  { name: 'Cocoa powder', quantity: '200', measureUnit: 'g', category: 'baking' },
  { name: 'Milk powder', quantity: '500', measureUnit: 'g', category: 'dairy' },
  { name: 'Shelf-stable milk', quantity: '2', measureUnit: 'l', category: 'dairy' },
  { name: 'Parmesan cheese (block)', quantity: '200', measureUnit: 'g', category: 'dairy' },
  { name: 'Cheddar cheese (block)', quantity: '250', measureUnit: 'g', category: 'dairy' },
  { name: 'Butter', quantity: '250', measureUnit: 'g', category: 'dairy' },
  { name: 'Ghee', quantity: '300', measureUnit: 'g', category: 'dairy' },
  { name: 'Eggs', quantity: '12', measureUnit: 'pcs', category: 'proteins' },
  { name: 'Canned tuna', quantity: '4', measureUnit: 'cans', category: 'proteins' },
  { name: 'Canned salmon', quantity: '2', measureUnit: 'cans', category: 'proteins' },
  { name: 'Chicken broth', quantity: '1', measureUnit: 'l', category: 'canned' },
  { name: 'Vegetable broth', quantity: '1', measureUnit: 'l', category: 'canned' },
  { name: 'Beef jerky', quantity: '150', measureUnit: 'g', category: 'proteins' },
  { name: 'Tofu (shelf-stable)', quantity: '2', measureUnit: 'packs', category: 'proteins' },
  { name: 'Sun-dried tomatoes', quantity: '200', measureUnit: 'g', category: 'canned' },
  { name: 'Pickles', quantity: '1', measureUnit: 'jar', category: 'condiments' },
  { name: 'Capers', quantity: '1', measureUnit: 'jar', category: 'condiments' },
  { name: 'Olives', quantity: '1', measureUnit: 'jar', category: 'condiments' },
  { name: 'Coconut milk', quantity: '2', measureUnit: 'cans', category: 'canned' },
  { name: 'Evaporated milk', quantity: '2', measureUnit: 'cans', category: 'dairy' },
  { name: 'Condensed milk', quantity: '1', measureUnit: 'can', category: 'dairy' },
  { name: 'Breadcrumbs', quantity: '300', measureUnit: 'g', category: 'baking' },
  { name: 'Panko', quantity: '300', measureUnit: 'g', category: 'baking' },
  { name: 'Tortillas', quantity: '10', measureUnit: 'pcs', category: 'grains' },
  { name: 'Pita bread', quantity: '6', measureUnit: 'pcs', category: 'grains' },
  { name: 'Nori sheets', quantity: '10', measureUnit: 'pcs', category: 'misc' },
  { name: 'Potatoes', quantity: '2', measureUnit: 'kg', category: 'produce' },
  { name: 'Onions', quantity: '1', measureUnit: 'kg', category: 'produce' },
  { name: 'Garlic', quantity: '3', measureUnit: 'bulbs', category: 'produce' },
  { name: 'Carrots', quantity: '1', measureUnit: 'kg', category: 'produce' },
  { name: 'Celery', quantity: '1', measureUnit: 'bunch', category: 'produce' },
  { name: 'Lemons', quantity: '6', measureUnit: 'pcs', category: 'produce' },
  { name: 'Limes', quantity: '6', measureUnit: 'pcs', category: 'produce' },
  { name: 'Apples', quantity: '6', measureUnit: 'pcs', category: 'produce' },
  { name: 'Bananas', quantity: '6', measureUnit: 'pcs', category: 'produce' },
  { name: 'Frozen peas', quantity: '500', measureUnit: 'g', category: 'produce' },
  { name: 'Frozen corn', quantity: '500', measureUnit: 'g', category: 'produce' },
  { name: 'Frozen spinach', quantity: '500', measureUnit: 'g', category: 'produce' },
  { name: 'Frozen berries', quantity: '500', measureUnit: 'g', category: 'produce' },
  { name: 'Vanilla extract', quantity: '60', measureUnit: 'ml', category: 'baking' },
  { name: 'Chocolate chips', quantity: '300', measureUnit: 'g', category: 'baking' },
  { name: 'Gelatin', quantity: '1', measureUnit: 'box', category: 'baking' },
  { name: 'Cornstarch', quantity: '400', measureUnit: 'g', category: 'baking' },
  { name: 'Sesame seeds', quantity: '100', measureUnit: 'g', category: 'spices' },
  { name: 'Sunflower seeds', quantity: '200', measureUnit: 'g', category: 'snacks' },
  { name: 'Chia seeds', quantity: '200', measureUnit: 'g', category: 'snacks' },
  { name: 'Flax seeds', quantity: '200', measureUnit: 'g', category: 'snacks' },
  { name: 'Trail mix', quantity: '300', measureUnit: 'g', category: 'snacks' },
  { name: 'Crackers', quantity: '200', measureUnit: 'g', category: 'snacks' },
  { name: 'Tomato sauce', quantity: '2', measureUnit: 'jars', category: 'canned' },
  { name: 'Pesto', quantity: '1', measureUnit: 'jar', category: 'condiments' },
  { name: 'BBQ sauce', quantity: '400', measureUnit: 'ml', category: 'condiments' },
  { name: 'Sriracha', quantity: '200', measureUnit: 'ml', category: 'condiments' },
  { name: 'Tahini', quantity: '300', measureUnit: 'g', category: 'condiments' },
  { name: 'Miso paste', quantity: '300', measureUnit: 'g', category: 'condiments' },
  { name: 'Anchovies', quantity: '1', measureUnit: 'jar', category: 'proteins' },
  { name: 'Canned mushrooms', quantity: '2', measureUnit: 'cans', category: 'canned' },
  { name: 'Artichoke hearts', quantity: '1', measureUnit: 'jar', category: 'canned' },
  { name: 'Roasted red peppers', quantity: '1', measureUnit: 'jar', category: 'canned' },
];

export const staplePreset = staplePresetDetailed.map((item) => item.name);
